spring:
  application:
    name: mix-fast-notificacao

aws:
  queue:
    name:
      pedido: mixfast-notificacao-pedido
      aprovado: mixfast-notificacao-pedido-pagamento-aprovado
      reprovado: mixfast-notificacao-pedido-pagamento-reprovado

server:
  port: 9083